### PR TITLE
A possible alternative

### PR DESCRIPTION
**Pull request by SFort**
I've changed the code so that furnace carts require soulsand for slowdown
gif-maker
screenshot uses quickly made [retexture](https://github.com/SFort/faster-minecarts/commit/968cfcefd4c936f028aa7107e1093ffb27087db4)
(also removed API dependency since mod only uses modloader)

### CODE REVIEW

**Comment by faultycore** [comment]
Good idea just having special blocks that mark an area for slow down. Personally I think Soulsand is a bit ugly but it's pretty intuitive. And it's weird having this system only for furnace carts and the other for all other carts, but I like it anyway. Maybe even do this for all other carts? But I'll have to think about it.

**Comment by SFort** [comment]
I was going to include honey blocks but for some reason you can't place rails on them

**Comment by faultycore** [comment]
> I was going to include honey blocks but for some reason you can't place rails on them

~~I think they did it because of [this bug](https://www.reddit.com/r/Minecraft/comments/drhcg4/wierd_honey_block_glitch_i_found_wierd_rails/), and instead of fixing the bug they simply said "let's just make it impossible to place rails on honey and slime blocks".~~
Actually it seems like it's [just a bug](https://bugs.mojang.com/browse/MC-163248)

And I just thought of an additional reason I like your idea, I was thinking another thing I could add to the mod was letting you control the speed similar to setting a throttle. And the soulsand let's you kind of do just that, or at least it let's you say "hey I wanna drive slow here" to appreciate the landscape or something.

**Comment by SFort** [comment]
currently even if you have a zero-tick piston you can't swap blocks underneath a rail without it breaking.
so i guess the only option for having a optionally slow track is to have a seperate track

**Comment by faultycore** [comment]
> currently even if you have a zero-tick piston you can't swap blocks underneath a rail without it breaking.
> so i guess the only option for having a optionally slow track is to have a seperate track

Yeah, I meant more like now you at least have the option to put a slow passage in your track, it's better than having no option at all I guess.

**Comment by SFort** [comment]
Ye you ware clear and it's a good thing, i just wanted to do piston stuff with my tracks

**Pull request merged**
